import type { MxWorkOrder } from "./types";

/**
 * Seed data for MX work orders (Phase 1–2).
 * Loaded by MxProvider as initial state.
 * workOrdersService will layer localStorage on top after hydration.
 */
export const MOCK_MX_WORK_ORDERS: MxWorkOrder[] = [
  // ── Open ──────────────────────────────────────────────────────────────────
  {
    id:                  "mxwo_001",
    woNumber:            "WO-0001",
    title:               "Replace hydraulic hose — Cat 330 #EQ-014",
    description:         "Main boom hydraulic hose showing wear and minor seepage at fitting. Must be replaced before next dig cycle. Equipment pulled from service.",
    category:            "corrective",
    priority:            "critical",
    status:              "in_progress",
    sourceType:          "manual",
    equipmentId:         "asset_001",
    equipmentLabel:      "Cat 330 Excavator #EQ-014",
    projectId:           "proj_highland_002",
    projectName:         "Highland Tower — Phase 2",
    requestedBy:         "Marcus Webb",
    requestedByUserId:   "user_owner_001",
    requestedDate:       "2026-04-10",
    neededByDate:        "2026-04-12",
    requiredSkills:      ["Hydraulic Systems"],
    readinessImpact:     "in_shop",
    opsBlocking:         true,
    assignedMechanicIds: ["cru_w_001"],
    createdAt:           "2026-04-10T07:00:00Z",
    updatedAt:           "2026-04-10T09:30:00Z",
  },
  {
    id:                  "mxwo_002",
    woNumber:            "WO-0002",
    title:               "Brake system inspection — Cat D6 Dozer #DZ-02",
    description:         "Scheduled inspection of brake system per PM checklist. Operator reported slight pull to the right under load.",
    category:            "inspection",
    priority:            "high",
    status:              "scheduled",
    sourceType:          "manual",
    equipmentId:         "asset_005",
    equipmentLabel:      "Cat D6 Dozer #DZ-02",
    projectId:           "proj_oakridge_001",
    projectName:         "Oakridge Industrial Complex",
    requestedBy:         "Marcus Webb",
    requestedByUserId:   "user_owner_001",
    requestedDate:       "2026-04-09",
    neededByDate:        "2026-04-14",
    scheduledStart:      "2026-04-14T07:00:00Z",
    scheduledEnd:        "2026-04-14T12:00:00Z",
    readinessImpact:     "scheduled_service",
    opsBlocking:         false,
    assignedMechanicIds: ["cru_w_002"],
    createdAt:           "2026-04-09T14:00:00Z",
    updatedAt:           "2026-04-11T08:00:00Z",
  },
  {
    id:                  "mxwo_003",
    woNumber:            "WO-0003",
    title:               "Replacement tracks — Cat D6T",
    description:         "Current tracks at 85% wear. Order and schedule replacement. Machine still operational with limited grading.",
    category:            "preventive",
    priority:            "medium",
    status:              "waiting_parts",
    sourceType:          "manual",
    equipmentId:         "asset_003",
    equipmentLabel:      "Concrete Pump #CP-3",
    projectId:           "proj_highland_002",
    projectName:         "Highland Tower — Phase 2",
    requestedBy:         "Marcus Webb",
    requestedByUserId:   "user_owner_001",
    requestedDate:       "2026-04-08",
    neededByDate:        "2026-04-20",
    readinessImpact:     "awaiting_parts",
    opsBlocking:         false,
    assignedMechanicIds: ["cru_w_001"],
    createdAt:           "2026-04-08T09:00:00Z",
    updatedAt:           "2026-04-10T10:00:00Z",
  },
  {
    id:                  "mxwo_004",
    woNumber:            "WO-0004",
    title:               "PM service — Tower Crane #CR-1",
    description:         "500-hour preventive maintenance service. Oil change, wire rope inspection, hoist brake check, boom sheave lubrication.",
    category:            "preventive",
    priority:            "medium",
    status:              "approved",
    sourceType:          "manual",
    equipmentId:         "asset_002",
    equipmentLabel:      "Tower Crane #CR-1",
    projectId:           "proj_highland_002",
    projectName:         "Highland Tower — Phase 2",
    requestedBy:         "Marcus Webb",
    requestedByUserId:   "user_owner_001",
    requestedDate:       "2026-04-07",
    neededByDate:        "2026-04-18",
    requiredSkills:      ["Diesel Engine"],
    readinessImpact:     "limited",
    opsBlocking:         false,
    assignedMechanicIds: [],
    createdAt:           "2026-04-07T11:00:00Z",
    updatedAt:           "2026-04-09T08:00:00Z",
  },
  {
    id:                  "mxwo_005",
    woNumber:            "WO-0005",
    title:               "Electrical fault — Crawler Crane #CR-7",
    description:         "Main electrical panel showing fault codes E-14 and E-22. Intermittent power loss to hoist motor. Crane pulled from service until resolved.",
    category:            "corrective",
    priority:            "critical",
    status:              "blocked",
    sourceType:          "alert",
    equipmentId:         "asset_004",
    equipmentLabel:      "Crawler Crane #CR-7",
    projectId:           "proj_oakridge_001",
    projectName:         "Oakridge Industrial Complex",
    requestedBy:         "Marcus Webb",
    requestedByUserId:   "user_owner_001",
    requestedDate:       "2026-04-10",
    neededByDate:        "2026-04-12",
    requiredSkills:      ["Electrical Diagnostics"],
    readinessImpact:     "down",
    opsBlocking:         true,
    assignedMechanicIds: ["cru_w_002"],
    completionNotes:     "Waiting for OEM technician — internal parts required. ETA 3 days.",
    createdAt:           "2026-04-10T06:30:00Z",
    updatedAt:           "2026-04-11T07:00:00Z",
  },
  {
    id:                  "mxwo_006",
    woNumber:            "WO-0006",
    title:               "Tire replacement — Scissor Lift #SL-9",
    description:         "Two tires flat, two showing significant sidewall cracking. Full set replacement required. Unit offline.",
    category:            "corrective",
    priority:            "high",
    status:              "open",
    sourceType:          "manual",
    equipmentId:         "asset_006",
    equipmentLabel:      "Scissor Lift #SL-9",
    projectId:           "proj_meridian_003",
    projectName:         "Meridian Bridge Rehab",
    requestedBy:         "Marcus Webb",
    requestedByUserId:   "user_owner_001",
    requestedDate:       "2026-04-09",
    neededByDate:        "2026-04-15",
    readinessImpact:     "at_risk",
    opsBlocking:         true,
    assignedMechanicIds: [],
    createdAt:           "2026-04-09T08:00:00Z",
    updatedAt:           "2026-04-09T08:00:00Z",
  },
  {
    id:                  "mxwo_007",
    woNumber:            "WO-0007",
    title:               "Oil change + filter service — Concrete Pump #CP-3",
    description:         "Routine 250-hour oil and filter service. Low priority — pump fully operational.",
    category:            "preventive",
    priority:            "low",
    status:              "triage",
    sourceType:          "manual",
    projectId:           "proj_highland_002",
    projectName:         "Highland Tower — Phase 2",
    requestedBy:         "Marcus Webb",
    requestedByUserId:   "user_owner_001",
    requestedDate:       "2026-04-11",
    neededByDate:        "2026-04-25",
    readinessImpact:     null,
    opsBlocking:         false,
    assignedMechanicIds: [],
    createdAt:           "2026-04-11T09:00:00Z",
    updatedAt:           "2026-04-11T09:00:00Z",
  },
  {
    id:                  "mxwo_008",
    woNumber:            "WO-0008",
    title:               "Wire rope inspection — Crawler Crane #CR-7",
    description:         "Annual wire rope inspection completed. Rope in acceptable condition with minor surface corrosion noted on section 3. Recommend re-inspection in 90 days.",
    category:            "inspection",
    priority:            "low",
    status:              "completed",
    sourceType:          "manual",
    equipmentId:         "asset_004",
    equipmentLabel:      "Crawler Crane #CR-7",
    projectId:           "proj_oakridge_001",
    projectName:         "Oakridge Industrial Complex",
    requestedBy:         "Marcus Webb",
    requestedByUserId:   "user_owner_001",
    requestedDate:       "2026-04-01",
    neededByDate:        "2026-04-05",
    actualStart:         "2026-04-03T07:00:00Z",
    actualEnd:           "2026-04-03T11:30:00Z",
    readinessImpact:     null,
    opsBlocking:         false,
    assignedMechanicIds: ["cru_w_002"],
    completionNotes:     "Inspection complete. Minor corrosion on section 3, documented. Schedule follow-up in 90 days.",
    createdAt:           "2026-04-01T08:00:00Z",
    updatedAt:           "2026-04-03T12:00:00Z",
  },
];

/** Next WO number counter — service tracks this in localStorage */
export const INITIAL_WO_COUNTER = 9;
